### ISSUE TITLE
Codespaces k3d cluster cannot be arc enabled

### ISSUE THREAD

**Issue by renato-marciano** [Azure-Samples/explore-iot-operations#47]
> Please provide us with the following information:
> ---------------------------------------------------------------

https://learn.microsoft.com/en-us/azure/iot-operations/deploy-iot-ops/howto-prepare-cluster?tabs=codespaces

Following the doc above for codespaces, I was not able to Arc enable the k3d cluster.

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

Follow instructions here for Codespaces:
https://learn.microsoft.com/en-us/azure/iot-operations/deploy-iot-ops/howto-prepare-cluster?tabs=codespaces

At Step 6: To Arc enable the cluster, I get the error below.

### Any log messages given by the failure
>

```
This operation might take a while...

The required pre-checks for onboarding have succeeded.
This CLI version does not support upgrading to Agents versions older than v1.14
Please select an agent-version >= v1.14 to upgrade to using 'az connectedk8s upgrade -g <rg_name> -n <cluster_name> --agent-version <at-least-1.14>'.
```

### Expected/desired behavior
> 

cluster to be Arc enabled

### Mention any other details that might be useful

Az version installed, after opening Codespaces. 

{
  "azure-cli": "2.55.0",
  "azure-cli-core": "2.55.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "azure-iot-ops": "0.2.0b1",
    "connectedk8s": "1.6.0",
    "k8s-extension": "1.5.3"
  }
}

Az cli 2.54.0 does not seem to have this issue.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jlian** [comment]
I cannot reproduce. I just created a new codespace and was able to connect it to Arc without running into the error you saw. Are you sure this is with a new cluster? Can you try with a new codespace?

My Azure CLI version, seems to match yours

```console
$ az --version
azure-cli                         2.55.0

core                              2.55.0
telemetry                          1.1.0

Extensions:
azure-iot-ops                    0.2.0b1
connectedk8s                       1.6.0
k8s-extension                      1.5.3

Dependencies:
msal                            1.24.0b2
azure-mgmt-resource             23.1.0b2

Python location '/opt/az/bin/python3'
Extensions directory '/home/codespace/.azure/cliextensions'

Python (Linux) 3.11.5 (main, Nov 29 2023, 03:42:00) [GCC 9.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

**Comment by mahomedalid** [comment]
I am also confirming I could create a cluster and register with arc. So probably a glitch?

**Comment by renato-marciano** [comment]
closing as i am able to register now with arc. Could have been fixed.
