### ISSUE TITLE
Industrial Data Simulator support for Bool parts

### ISSUE THREAD

**Issue by mahomedalid** [Azure-Samples/explore-iot-operations#56]
Support for boolean values.

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior

OPCUA Payloads use boolean to define tags (ex. MachineStatus.Automatic) and it is part of the reference:

https://reference.opcfoundation.org/Core/Part3/v104/docs/8.8

### Mention any other details that might be useful

Support for boolean could be non-trivial using golang/ast, but can be achieved by providing a special "string" that gets mapped.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ethanperry1** [comment]
Hi @mahomedalid, I will look into adding this to the industrial data simulator. Thanks for the feedback

**Comment by mahomedalid** [comment]
Thanks @ethanperry1 ! btw, I submitted this PR - https://github.com/Azure-Samples/explore-iot-operations/pull/55
