### ISSUE TITLE
Disable Local Auth in Event Hub namespaces.

### ISSUE THREAD

**Issue by tonybaloney** [Azure-Samples/explore-iot-operations#75]
If  the client is using Event Hub cryptographic keys, or Entra ID/ Managed ID-- can we please disable local auth in the Bicep template here https://github.com/Azure-Samples/explore-iot-operations/blob/125ada5db88f6359e6a31d1e88c27869e8b30104/tutorials/mq-realtime-fabric-dashboard/deployEdgeAndCloudResources.bicep#L363-L363

See : https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.EventHub.DisableLocalAuth/

Tracking issue for:
- [ ] https://github.com/Azure-Samples/explore-iot-operations/security/code-scanning/1

**Comment by veyalla** [comment]
This doesn't work with Fabric Real-Time Intelligence yet which needs SAS token based auth.
